const STORE = {
    patientName: "Laura",
    patientId: "x029",
    familyMembers: [
        {
            user: "laurasmom12",
            userId: "i83n",
        },
        {
            user: "laurasdaughter44",
            userId: "7h2g",
        },
        {
            user: "laurasson99",
            userId: "l002",
        },
        {
            user: "laura",
            userId: "77zx",
        },
    ],
    medicalContacts: [
        {
            contact: "Carol Zimmerman",
            title: "Doctor",
            spec: "Oncologist",
            office: {
                name: "Zimmerman Practice",
                phone: 3129179888,
                address: " 1234 Milwaukee Ave Chicago IL 60625",
                notes: null,
            },
            hospital: {
                name: "Northwestern Hospital",
                address: "1234 Nowhere Dr Evanston IL 60606",
                affiliatedContacts: ["Jim Smith", "Carol Zimmerman"],
            },
            notes: null,
        },
        {
            contact: "Jim Smith",
            title: "Doctor",
            spec: "Primary",
            office: {
                name: "Smith & Lee Physicans",
                phone: 3129179888,
                address: " 1234 Milwaukee Ave Chicago IL 60625",
                notes: null,
            },
            hospital: {
                name: "Northwestern Hospital",
                address: "1234 Nowhere Dr Evanston IL 60606",
                affiliatedContacts: ["Jim Smith", "Carol Zimmerman"],
            },
            notes: null,
        },
        {
            contact: "Alice Walker",
            title: "Nurse",
            spec: "In-home care",
            office: {
                name: null,
                phone: 3127781000,
                address: null,
                notes: "Alice comes for eight hours on Tuesdays and Thursdays",
            },
            hospital: null,
            notes: null,
        },
    ],
    calendar: [
        {
            start: "2020-09-23 09:00:00",
            duration: "00:50:00",
            note: "Appointment",
            contact: "Doctor Smith",
        },
        {
            start: "2020-09-23 13:30:00",
            duration: "00:50:00",
            note: "Appointment",
            contact: "Doctor Fisher",
        },
        {
            start: "2020-09-24 09:00:00",
            duration: "00:50:00",
            note: "Appointment",
            contact: "Doctor Green",
        },
        {
            start: "2020-09-23 09:00:00",
            duration: "00:50:00",
            note: "Appointment",
            contact: "Doctor Smith",
        },
    ],
    medications: [
        {
            name: "Xybeopene",
            dose: "10mg",
            takeDaily: true,
            takeWithFood: false,
            hasRefill: false,
            refillBefore: '2020-09-29',
            contact: "Carol Zimmerman",
            added: '2019-02-09',
        },
        {
            name: "Neropene",
            dose: "50mg",
            takeDaily: true,
            takeWithFood: true,
            hasRefill: true,
            refillBefore: '2020-09-29',
            contact: "Jim Smith",
            added: '2016-05-23',
        },
        {
            name: "Rydol",
            dose: "10mg",
            takeDaily: false,
            takeWithFood: false,
            hasRefill: false,
            refillBefore: '2020-10-02',
            contact: "Jim Smith",
            added: '2017-09-09'
        },
        {
            name: "Xybeorene",
            dose: "10mg",
            takeDaily: true,
            takeWithFood: false,
            hasRefill: true,
            refillBefore: '2020-09-29',
            contact: "Carol Zimmerman",
            added: '2018-12-19'
        },
        {
            name: "Nerozene",
            dose: "50mg",
            takeDaily: true,
            takeWithFood: true,
            hasRefill: true,
            refillBefore: '2020-09-29',
            contact: "Jim Smith",
            added: '2019-08-29',
        },
        {
            name: "Rybol",
            dose: "10mg",
            takeDaily: false,
            takeWithFood: false,
            hasRefill: true,
            refillBefore: '2020-10-02',
            contact: "Jim Smith",
            added: '2019-03-23'
        },
        {
            name: "Xypena",
            dose: "1mg",
            takeDaily: false,
            takeWithFood: true,
            hasRefill: true,
            refillBefore: '2020-09-29',
            contact: "Carol Zimmerman",
            added: '2019-02-09',
        },
        {
            name: "Nerpen",
            dose: "5mg",
            takeDaily: false,
            takeWithFood: false,
            hasRefill: true,
            refillBefore: '2020-09-29',
            contact: "Jim Smith",
            added: '2016-05-23',
        },
        {
            name: "Clypena",
            dose: "2mg",
            takeDaily: false,
            takeWithFood: false,
            hasRefill: true,
            refillBefore: '2020-09-29',
            contact: "Carol Zimmerman",
            added: '2019-02-09',
        },
        {
            name: "Nerpone",
            dose: "15mg",
            takeDaily: false,
            takeWithFood: false,
            hasRefill: true,
            refillBefore: '2020-09-29',
            contact: "Jim Smith",
            added: '2016-05-23',
        },
    ],
    pharmacy: {
        address: "124 Pharmacy Lane Chicago, IL 60625",
        hours: "9:00AM to 5:00PM",
        pharmacist: "Dr. Kim",
    },
};

export default STORE;